id: P0A16063C
initial_creation_type: ocr
source_metadata:
  volumes:
    41b72c635ddb449d81251b870bb88070:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: ཤེས་རབ་སྙིང་པོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1682
      volume_number: 56
